<?php

namespace common\models;

use common\models\dao\ImageDao;
use common\models\dao\PostsDao;
use common\models\union\dao\ResourceDao;
use common\models\union\Resource;
use yii\base\Model;
use yii\web\UploadedFile;

/**
 * ContactForm is the model behind the contact form.
 */
class UploadForm extends Model
{

    /**
     * @var UploadedFile
     */
    public $imageFile;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['imageFile'], 'file', 'skipOnEmpty' => true, 'extensions' => ['png','jpg','jpeg'], "maxSize" => 2097152],
        ];
    }

    /**
     * @return Resource
     * @throws \Exception
     */
    public function upload($postsId)
    {
        if(!$this->validate() ){
            throw new \Exception($this->errors['imageFile'][0]);
        }
        $md5 = md5(file_get_contents($this->imageFile->tempName));
        $resource = ImageDao::getByFileMd5AndUserId($md5);
        if($resource){
            return $resource;
        }
        $filename = $md5;
        $path = "/home/work/dashboard/resource/beauty/";
        if(!file_exists($path)){
            $result = mkdir($path,0777,true);
            if(!$result){
                throw new \Exception('创建文件目录错误');
            }
        }
        $realPath = $path . $filename . '.' . $this->imageFile->extension;
        $this->imageFile->saveAs($realPath);


        $resource = new Image();
        $resource->name = $this->imageFile->baseName;
        $resource->file_md5 =  $md5;
        $resource->file_size = $this->imageFile->size;
        $resource->file_name = $filename . '.' . $this->imageFile->extension;
        $resource->type =ImageDao::TYPE_IMAGE;
        list($width, $height, $type, $attr) = getimagesize($realPath);
        $resource->image_width = $width;
        $resource->image_height =$height;
        if($postsId){
            $resource->posts_id = $postsId;
        }
        $resource->image_ext = $this->imageFile->extension;
        $resource->create_time = date('Y-m-d H:i:s');
        $resource->modified_time = date('Y-m-d H:i:s');
        $result = $resource->save();
        if(!$result){
            throw new \Exception(json_encode($resource->getErrors()));
        }
        if($postsId){
           PostsDao::updateImageCount($postsId);
        }
        return $resource;
    }
}
